name: Deploy Backend to EC2

on:
  push:
    branches:
      - master   # Trigger on pushes to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # 🚀 Deploy to EC2 using SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}           # EC2 host (e.g., ubuntu@51.21.168.212)
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}        # Private key
          port: 22
          script: |
                cd ${{ secrets.PROJECT_PATH }}
                git fetch --all
                git reset --hard origin/master    # ⚡️ force sync with GitHub
                npm install --production
                pm2 restart backend || pm2 start server.js --name backend
